language: node_js
node_js:
  - 10.22.1
branchs:
  - master
addons:
  apt:
    packages:
    - sshpass
cache:
  directories:
    - node_modules
install:
  "yarn install"
script:
  - "yarn run build"
after_success:
  - ./script/deploy.sh